config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  root 'home#index'
  match '/', to: 'home#index', via: 'get', as: 'home'
  match 'search', to: 'search#index', via: [:get, :post], as: 'search'
  match 'search/found/', to: 'search#show', via: 'get', as: 'show_search'
  match 'search/slack/', to: 'search#slack', via: [:get, :post], as: 'slack_search'
  match 'dashboard', to: 'dashboard#index', via: 'get', as: 'dashboard'
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  resources :teams
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @teamcount = Team.where('user_id = ?', @user.id).count
  end

  def settings
    @user = current_user
    @teams = current_user.teams
  end

  def api
    @user = current_user
  end

  def get_token
    @user = current_user
    @user.set_token
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def token_button(user)
    if user && user.token.present?
      button_to "Get New Token", get_token_path, class: "btn btn-info", remote: true
    else
      button_to "Get Token", get_token_path, class: "btn btn-success", remote: true
    end
  end
end

app/views/dashboard/_api_data.html.erb
  <div class="row">
    <div class="col-xs-12">
      <h2>API Token</h2>
      <%= token_button @user %>
    </div>
  </div>
  <div class="row">
      <label for="user_token" class="token"><h4>API Token:</h4></label>
      <div class="col-xs-12">
        <%= text_field(:user, :token, class: "form-control", readonly: true) %>
      </div>
  </div>
  <br/>
  <div class="row">
    <h4>GET Gifs</h4>
    <p> </p>
    <div class="col-xs-12">
      <div class="well well-sm">
        http://reactif.me/api/gifs.json?q=<code>search terms</code>&token=<code>your token</code>
      </div>
      it will return an object like this one:
      <div class="well well-sm">
        {<br/>
          "word": "word",<br/>
          "url": "http://www.reactiongifs.com/wp-content/uploads/2012/12/you-got-it-dude.gif"<br/>
        }
      </div>
    </div>
  </div>

app/views/dashboard/_dashboard_modal.html.erb
<div class="modal fade" id="dashboard-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="dashboard-modal-title"></h4>
      </div>
      <div class="modal-body" id="dashboard-modal-body">
        
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_team_form.html.erb
<%= form_for @team do |f| -%>
  <div class="input-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="input-group">
    <%= f.label :domain %>
    <%= f.text_field :domain, class: 'form-control' %>
  </div>
  <div class="input-group">
    <%= f.label :webhook, "Webhook" %>
    <%= f.text_field :webhook, class: 'form-control' %>
  </div>
  <br>
  <div class="input-group">
    <%= f.submit class: 'btn btn-success btn-sm' %>
  </div>
<% end %>

app/views/dashboard/_team_row.html.erb
<tr id="team_<%= team.id %>">
  <td><%= team.name %></td>
  <td><%= team.domain %></td>
  <td><%= team.webhook %></td>
  <td>
    <div class="btn-group btn-group-sm">
      <%= link_to "Edit", edit_team_path(team), remote: true, class: "btn btn-default" %>
      <%= link_to "Delete", team_path(team), method: :delete, class: "btn btn-danger" %>
    </div>
  </td>
</tr>

app/views/dashboard/_team_table.html.erb
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <td>Name</td>
                <td>Domain</td>
                <td>Web Hook</td>
            </tr>
        </thead>
        <tbody>
            <% unless @teams.empty? %>
                <% @teams.each do |team| %>
                    <%= render 'team_row', team: team  unless team.new_record? %>
                <% end %>
            <% end %>
        </tbody>
    </table>
</div>

app/views/dashboard/api.html.erb
<div class="row dashboard">
    <div class="col-sm-2 sidebar">
        <ul class="nav nav-sidebar">
            <li><%= link_to 'Overview', dashboard_path %></li>
            <li><%= link_to 'Settings', dashboard_settings_path %></li>
            <li class="active"><%= link_to 'API', dashboard_api_path %></li>
        </ul>
    </div>
    <div class="col-sm-10">
        <h1>Dashboard for <%= @user.name %></h1>
        <hr>
        <%= render 'api_data' %>
    </div>
</div>

app/views/dashboard/get_token.js.erb
$("#user_token").val("<%= @user.token %>");

app/views/dashboard/index.html.erb
<div class="row dashboard">
    <div class="col-sm-2 sidebar">
        <ul class="nav nav-sidebar">
            <li><%= link_to 'Overview', dashboard_path %></li>
        </ul>
    </div>
    <div class="col-sm-10">
        <h1>Dashboard for <%= @user.name %></h1>
        <hr>
        <h2>
            Teams
            <%= link_to new_team_path, remote: true, class: "btn btn-success btn-circle btn-sm" do %>
                <span class="glyphicon glyphicon-plus"></span>
            <% end %>
        </h2>
        <%= render 'team_table' %>
        </div>
    </div>
</div>

<%= render 'dashboard_modal' %>

app/views/dashboard/settings.html.erb
<div class="row dashboard">
    <div class="col-sm-2 sidebar">
        <ul class="nav nav-sidebar">
            <li><%= link_to 'Overview', dashboard_path %></li>
            <li class="active"><%= link_to 'Settings', dashboard_settings_path, class: "menu_settings" %></li>
            <li><%= link_to 'API', dashboard_api_path %></li>
        </ul>
    </div>
    <div class="col-sm-10">
        <h1>Dashboard for <%= @user.name %></h1>
        <hr>
        <h2>Teams</h2>
        <%= render 'team_table' %>
    </div>
</div>