config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  root 'home#index'
  match '/', to: 'home#index', via: 'get', as: 'home'
  match 'search', to: 'search#index', via: [:get, :post], as: 'search'
  match 'search/found/', to: 'search#show', via: 'get', as: 'show_search'
  match 'search/slack/', to: 'search#slack', via: [:get, :post], as: 'slack_search'
  match 'dashboard', to: 'dashboard#index', via: 'get', as: 'dashboard'
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
  resources :teams
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_url, class: "navbar-brand" do %>
          <b>REACT<span style="font-weight: 300;">IF</span></b>
        <% end %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <% if user_signed_in? %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                Options
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Dashboard", root_path %></li>
                <li><%= link_to "Edit profile", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
              </ul>
            <% else %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                Login
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><a data-toggle="modal" data-target="#usersignup">Register</a></li>
                <li><a data-toggle="modal" data-target="#usersignin">Sign in</a></li>
              </ul>
            <% end %>
          </li>
        </ul>
        <div class="navbar-form navbar-right" role="search">
          <%= render partial: 'shared/search_form' %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_login_overlay.html.erb
<% @user = User.new %>
<!-- sign in modal overlay -->
<!-- user sign in -->
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="usersignin" id="usersignin" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    <h3 align="center"> User Sign In</h3>
      <%= form_for(@user, as: @user, url: session_path(@user), method: :post) do |f| %>
      <div class="row">
      <div class="form-group col-xs-8 col-xs-offset-2" align="center">
      <%= f.label :email, class: 'control-label pull-left' %><br />
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    </div>

      <div class="row">
      <div class="form-group col-xs-8 col-xs-offset-2" align="center">
      <%= f.label :password, class: 'control-label pull-left' %><br />
      <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
    </div>
    </div>

      <div class="row">
      <div class="form-group col-xs-8 col-xs-offset-2" align="center">
        <%= f.check_box :remember_me %> <%= f.label :remember_me, class: "dark"%>
      </div>
    </div>
      <div class="row">
      <div class="form-group col-xs-6 col-xs-offset-3" align="center">
        <%= f.submit "Sign in", class: 'btn-primary', data: { disable_with: "processing..." } %>
      </div>
      </div>
      <div class="row">
		  <div class="form-group col-xs-6 col-xs-offset-3" align="center">
		  </div>
      </div>
    <% end %>
    </div>
  </div>
</div>
<!-- user registration-->
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="usersignup" id="usersignup" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <h3 align="center">User Registration</h3>
      <%= form_for(@user, as: @user, url: registration_path(@user)) do |f| %>
      <div class="row">
      <div class="form-group col-xs-8 col-xs-offset-2" align="center">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Username" %>
      </div>
      </div>

      <div class="row">
      <div class="form-group col-xs-8 col-xs-offset-2" align="center">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', placeholder: "Email" %>
      </div>
      </div>

      <div class="row">
      <div class="form-group col-xs-8 col-xs-offset-2" align="center">
        <%= f.label :password, 'Password (minimum 8 characters)' %>
        <%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder: "Password" %>
      </div>
      </div>
        <div class="row">
        <div class="form-group" align="center">
          <%= f.submit "Sign up", class: 'btn-primary', data: { disable_with: "saving..." } %>
        </div>
        </div>
        <div class="row">
        <div class="form-group col-xs-6 col-xs-offset-3" align="center">
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reactif</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: 'layouts/header' %>
    <% unless user_signed_in? %>
      <%= render partial: 'layouts/login_overlay' %>
    <% end %>
    <% if notice or alert %>
      <%= custom_bootstrap_flash %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>